fire/urls.py
from django.urls import path
from . import views
app_name='fire'

urlpatterns=[
    path('',views.home,name='home'),
    path('<int:item_id>/',views.details,name='details'),
    path('<int:item_id>/transfer',views.transferitem,name='transfer'),
    path('<int:item_id>/return',views.returnitem,name='return'),
    path('history',views.transact,name='transact'),
    # path(r'<int:tran.client.client_id>/',views.transaction_details,name='trans_history'),

]

inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from fire import views
from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fire.urls')),
    path('items/',views.itemsView.as_view()),
    path('transactions/',views.transactionsView.as_view())
]

urlpatterns=format_suffix_patterns(urlpatterns)

fire/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    category=models.CharField(max_length=30)
    def __str__(self):
        return self.category

class Item(models.Model):
    item_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    def __str__(self):
        return self.name

class Client(models.Model):
    place=models.CharField(max_length=50)
    description=models.CharField(max_length=100)
    def __str__(self):
        return self.place

class Transaction(models.Model):
    trans_id=models.AutoField(primary_key=True)
    quantity=models.IntegerField()
    time=models.DateTimeField(auto_now=True)
    item=models.ForeignKey(Item,on_delete=models.CASCADE,blank=False,null=False)
    client=models.ForeignKey(Client,on_delete=models.CASCADE,blank=False,null=False)
    def __str__(self):
        return ('{} ,{} ,{}'.format(self.item.name,self.client.place,self.time))
        

fire/views.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from .models import Category,Item,Client,Transaction
from .serializers import itemsSerializer,transactionSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
# Create your views here.
def home(request):
    items=Item.objects.all()
    context={'items':items}
    return render(request,'fire/home.html',context)

def details(request,item_id):
    item=get_object_or_404(Item,pk=item_id)
    clients=Client.objects.all()
    context={'item':item,'clients':clients}
    return render(request,'fire/details.html',context)

def transferitem(request,item_id):
    client=Client.objects.get(place=request.POST.get('client'))
    item=Item.objects.get(pk=item_id)
    quantity=request.POST.get('quantity')
    transaction=Transaction(quantity=quantity,item=item,client=client)
    transaction.save()
    item.quantity=item.quantity-int(quantity)
    item.save()
    context={'transaction':transaction,'quantity':quantity,'item':item,'client':client}
    return render(request,'fire/transferitem.html',context)

def returnitem(request,item_id):
    client=Client.objects.get(place=request.POST.get('client'))
    item=Item.objects.get(pk=item_id)
    quantity=request.POST.get('quantity')
    transaction=Transaction(quantity=quantity,item=item,client=client)
    transaction.save()
    item.quantity=item.quantity+int(quantity)
    item.save()
    context={'transaction':transaction,'quantity':quantity,'item':item,'client':client}
    return render(request,'fire/returnitem.html',context)
 ##transaction history page
def transact(request):
    clients=Client.objects.all()
    trans=Transaction.objects.all()
    context={'clients':clients,'trans':trans}
    return render(request,'fire/trans_details.html',context)
def transaction_details(request,client_id):
    clients=get_object_or_404(Client,pk=client_id)
    transactions=Transaction.objects.all()
    context={'clients':clients,'transactions':transactions}
    return render(request,'fire/transactions.html',context)
# api views
class itemsView(APIView):
    def get(self,request):
        items=Item.objects.all()
        serializer=itemsSerializer(items,many=True)
        return Response(serializer.data)
    def post(self,request):
        pass
class transactionsView(APIView):
    def get(self,request):
        transactions=Transaction.objects.all()
        serializer=transactionSerializer(transactions,many=True)
        return Response(serializer.data)
    def post(self,request):
        pass

fire/templates/fire/base.html
{% load static %}
<html>
	<head>
		
		<title>{%block title%}
		{%endblock%}</title>
		
		<script type="text/javascript" src="{% static 'fire/jquery-3.3.1.min.js' %}"></script>		
		<script type="text/javascript" charset="utf8" src="{% static 'fire/DataTables/datatables.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'fire/DataTables/datatables.css' %}"/>
		<script type="text/javascript" charset="utf8" src="{% static 'fire/js/bootstrap.min.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'fire/css/bootstrap.min.css' %}"/>
		<link rel="icon" href="{% static 'fire/logo2.ico' %}">
	</head>
	<body>
	
	<center><a class="btn btn-primary" href="/">HOME</a></center>
	{% block content%}
	{% endblock %}
	</body>
</html>

fire/templates/fire/details.html
{% extends 'fire/base.html' %}
{% block content %}
<center>
<div class="card" style="width: 50rem;">
<div class="card-body">
<form action="transfer" method="post">
<div class="card-header">TRANSFER {{ item.name }}</div>
{% csrf_token %}
<input type="hidden" name="item" value="{{ item.name }}">
<div class="form-group">
<label for="quantity">Quantity</label>
<input type="number" class="form-control" value="1" id="quantity" name="quantity" min="1" max="{{ item.quantity }}"/> 
</div>
<div class="form-group">
<label for="client">Client</label>
<select name="client" class="form-control" id="client">
{% for client in clients %}
<option value="{{ client.place }}">{{ client.place }}</option>
{% endfor %}
</select>
</div>
<input type="submit" class="btn btn-primary" value="TRANSFER">
</form>
</div>
</div>
</center>
<br/>
<center>
<div class="card" style="width: 50rem;">
<div class="card-body">
<form action="return" method="post">
<div class="card-header">RETURN {{ item.name }}</div>
{% csrf_token %}
<input type="hidden" name="item" value="{{ item.name }}">
<div class="form-group">
<label for="quantity">Quantity</label>
<input type="number" class="form-control" value="1" id="quantity" name="quantity" min="1" max="{{ item.quantity }}"/>
</div>
<div class="form-group">
<label for="client">Client</label>
<select name="client" class="form-control" id="client">
{% for client in clients %}
<option value="{{ client.place }}">{{ client.place }}</option>
{% endfor %}
</select>
</div>
<input type="submit" class="btn btn-primary" value="RETURN">
</form>
</div>
</div>
</center>
{% endblock %}

fire/templates/fire/home.html
{% extends 'fire/base.html' %}
{%block title%}
ITEMS
{%endblock%}
{% block content %}
	<script type="text/javascript">
			$(document).ready(function() {
    				$('#example').DataTable();
			} );
	</script>
	{% if items %}
	<table id="example" class="table table-bordered display" style="width:100%">
    		<thead class="thead-dark">
            		<tr>
				<th>ID</th>
                		<th>Name</th>
				<th>Category</th>
				<th>Quantity</th>
            		</tr>
        	</thead>
        	<tbody>
    		{% for item in items %}
		<tr>
        		<td>{{ item.item_id }}</td><td><a href="{% url 'fire:details' item.item_id %}">{{ item.name }}</a></td><td>{{ item.category.category }}</td><td>{{ item.quantity }}</td></a>
	  	</tr>    
	{% endfor %}
		</tbody>
		<tfoot>
            		<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Category</th>
				<th>Quantity</th>
            		</tr>
        	</tfoot>
	</table>
	{% else %}
    		<p>No details are available.</p>
	{% endif %}
{% endblock %}

fire/templates/fire/returnitem.html
{% extends 'fire/base.html' %}
{% block content %}
<div class="alert alert-primary" role="alert">
<h1>TRANSACTION : {{ transaction.trans_id }}<h1> Return {{ quantity }} {{ item.name }}s to {{ client.place }} successful!
<div>
{% endblock %}

fire/templates/fire/trans_details.html
{% extends 'fire/base.html' %}
{%block title%}
client transaction history
{%endblock%}
{% block content %}
	<script type="text/javascript">
			$(document).ready(function() {
    				$('#example').DataTable();
			} );
	</script>
	{% if trans %}
	<table id="example" class="table table-bordered display" style="width:100%">
    		<thead class="thead-dark">
            		<tr>
				
                		<th>Name</th>
				<th>Place</th>
				<th>Item</th>
            		</tr>
        	</thead>
        	<tbody>
    		{% for tran in trans %}
			 
		<tr>
        		
               
                <td>{{ tran.client }}</td>
                <td>{{tran.client.description}}</td>
               <td>{{tran.item.name}}</td>
	  	</tr>    
		  
	{% endfor %}
		</tbody>
		<tfoot>
            		<tr>
				<	<th>Name</th>
				<th>Place</th>
				
            		</tr>
        	</tfoot>
	</table>
	{% else %}
    		<p>No details are available.</p>
	{% endif %}
{% endblock %}

fire/templates/fire/transactions.html
{% extends 'fire/base.html' %}
{%block title%}
transactions
{%endblock%}
{% block content %}
	<script type="text/javascript">
			$(document).ready(function() {
    				$('#example').DataTable();
			} );
	</script>
	{% if transactions %}
	<table id="example" class="table table-bordered display" style="width:100%">
    		<thead class="thead-dark">
            		<tr>
				
                		<th>CLIENT</th>
				<th>ITEM</th>
				<th>Quantity</th>
                
            		</tr>
        	</thead>
        	<tbody>
    		{% for client in clients %}
		<tr>
        		   <td>{{ transaction.client }}</td>
             
                <td>{{ transaction.item.name }}</td>
                <td>{{ transaction.item.quantity }}</td></a>
	  	</tr>    
	{% endfor %}
		</tbody>
		<tfoot>
            		<tr>
				<th>client</th>
				<th>item</th>
				
				<th>Quantity</th>
            		</tr>
        	</tfoot>
	</table>
	{% else %}
    		<p>No details are available.</p>
	{% endif %}
{% endblock %}

fire/templates/fire/transferitem.html
{% extends 'fire/base.html' %}
{% block content %}
<div class="alert alert-primary" role="alert">
<h1>TRANSACTION : {{ transaction.trans_id }}<h1>  Transfer {{ quantity }}, {{ item.name }}s to {{ client.place }} succesful!
<div>
{% endblock %}